version: "2.16"

services:
  apache-php:
    image: tenant-portal-2-php
    volumes:
      # Persistent data
      - tenant-db:/var/www/html/db
    restart: unless-stopped
    ports:
      - 3010:80

volumes:
  tenant-db: