version: "2"

services:

  apache-php:
    # build from current directory
    build: .
    image: tenant-portal-2-php
    volumes:
      # Persistent data
      - tenant-db:/var/www/html/db
    restart: unless-stopped
    ports:
      - 3010:80

volumes:
  tenant-db: